spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: application:microservicecloud-config-dept-client
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com #自定义服务名称
    prefer-ip-address: true  #访问路径显示ip地址

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: application:microservicecloud-config-dept-client
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com #自定义服务名称
    prefer-ip-address: true  #访问路径显示ip地址

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$